$(document).ready(function(){
         $('<div class="row">'
         +'      <div class="large-4 medium-4 ftcolumn columns">'
         +'          <h5>Passt der Studiengang zu mir?</h5>'
         +'          <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed</p>'
         +'          <a href="#" class="button">Studienberater starten</a>'
         +'        </div>'
         +'      <div class="large-4 medium-4 ftcolumn columns">'
         +'          <h5>Studienberatung</h5>'
         +'           <div class="row">'
         +'              <div class="large-6 medium-6 columns">'
         +'                <ul class="vcard">'
         +'                  <li class="fn">Andrea Krajewski</li>'
         +'                  <li class="txtsmall">Studienfachberaterin</li>'
         +'                  <li class="tel">+49 6151 169 450</li>'
         +'                  <li class="street-address hide">Max-Planck-Straße 2</li>'
         +'                  <li class="hide"><span class="zip">64807</span>, <span class="state">Dieburg</span></li>'
         +'                  <li class="state hide">Hessen</li>'
         +'                </ul>'
         +'                <a href="#" class="button">Kontakt</a>'
         +'              </div>'
         +'              <div class="large-6 medium-6 columns">'
         +'                <ul class="vcard">'
         +'                  <li class="fn">Enes Ünal</li>'
         +'                  <li class="txtsmall">Studentischer Berater</li>'
         +'                  <li>@imd</li>'
         +'                </ul>'
         +'                <a href="#" class="button">Kontakt</a>'
         +'              </div>'
         +'            </div>'
         +'        </div>'
         +'        <div class="large-4 medium-4 ftcolumn columns">'
         +'          <h5>In Verbindung bleiben</h5>'
         +'          <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed</p>'
         +'          <a href="#" class="sociallink facebook">Facebook</a>'
         +'          <a href="#" class="sociallink twitter">Twitter</a>'
         +'          <a href="#" class="sociallink vimeo">Vimeo</a>'
         +'        </div>'
         +'        <hr>'
         +'        <div class="large-8 small-8 columns copyright">'
         +'          <p class="txtsmall">© 2014 h_da - Ein <a href="#">IMD-Projekt</a></p>'
         +'        </div>'
         +'        <div class="large-4 small-4 columns txtright copyright">'
         +'          <p class="txtsmall"><a href="#">Impressum</a></p>'
         +'        </div>'
         +'      </div>').appendTo('footer');
});