$(document).ready(function(){
         $('<div class="row">'
         +'<nav class="top-bar" data-topbar>'
         +'     <ul class="title-area">'
         +'       <!-- Title Area -->'
         +'       <li class="name">'
         +'         <h1>'
         +'           <a href="#">'
         +'             <img src="img/hda_logo_white.svg" alt="h_da">'
         +'             <span class="regular show-for-small-only title">IMD</span>'
         +'             <span class="regular show-for-medium-up title">Interactive Media Design</span>'
         +'           </a>'
         +'         </h1>'
         +'       </li>'
         +'       <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>'
         +'     </ul>' 
         +'     <section class="top-bar-section">'
         +'       <ul class="left">'
         +'         <li class="has-dropdown">'
         +'           <a href="studium.html">Studium</a>'
         +'           <ul class="dropdown">'
         +'             <li><a href="studienverlauf.html">Studienverlauf</a></li>'
         +'             <li><a href="projekte.html">Projekte</a></li>'
         +'             <li><a href="kurse.html">Kurse</a></li>'
         +'             <li><a href="dozenten.html">Dozenten</a></li>'
         +'             <li><a href="ausstattung.html">Ausstattung</a></li>'
         +'           </ul>'
         +'         </li>'
         +'          <li><a href="berufsausblick.html">Berufsausblick</a></li>'
         +'          <li><a href="bewerbung.html">Bewerbung</a></li>'
         +'          <li><a href="#">Events</a></li>'
         +'          <li><a href="#">Magazin</a></li>'
         +'       </ul>'
         +'     </section>'
         +'     <section class="top-bar-section">'
         +'       <ul class="right">'
         +'          <li><a href="#"><span class="active">De</span> / En</a></li>'
         +'       </ul>'
         +'     </section>'
         +'   </nav>'
         +' </div>').appendTo('header#pagenav');
});