$(document).ready(function(){

     /* $('<div class="row">'
      +'  <div class="own_size column">'
      +'    <ul>'
      +'      <li class="heading">Magazin</li>'
      +'      <li><a href="#">Aktuelle Beiträge</a></li>'
      +'      <li><a href="#">Archiv</a></li>'
      +'    </ul>'
      +'  </div>'
      +'  <div class="own_size column">'
      +'    <ul>'
      +'      <li class="heading">Studium</li>'
      +'      <li><a href="#">Studiengänge</a></li>'
      +'      <li><a href="#">Projektarchiv</a></li>'
      +'      <li><a href="#">Online-Studienberatung</a></li>'
      +'      <li><a href="#">Studieren im Ausland</a></li>'
      +'    </ul>'
      +'  </div>'
      +'  <div class="own_size column">'
      +'    <ul>'
      +'      <li class="heading">Campus</li>'
      +'      <li><a href="#">Campuskarte</a></li>'
      +'      <li><a href="#">Arbeitsräume</a></li>'
      +'      <li><a href="#">Enspannung & Sport</a></li>'
      +'      <li><a href="#">Wohnen</a></li>'
      +'      <li><a href="#">Karriere</a></li>'
      +'      <li><a href="#">Professoren & Mitarbeiter</a></li>'
      +'    </ul>'
      +'  </div>'
      +'  <div class="own_size column">'
      +'    <ul>'
      +'      <li class="heading">Events</li>'
      +'      <li><a href="#">Eventübersicht</a></li>'
      +'      <li><a href="#">MediaMonday</a></li>'
      +'      <li><a href="#">Sience Wednesday</a></li>'
      +'      <li><a href="#">Zeitraum TV</a></li>'
      +'      <li><a href="#">mediale*</a></li>'
      +'      <li><a href="#">Campus Radio</a></li>'
      +'    </ul>'
      +'  </div>'
      +'  <div class="own_size column">'
      +'    <ul>'
      +'      <li class="heading">Magazin</li>'
      +'      <li><a href="#">iKum</a></li>'
      +'      <li><a href="#">Kooparationen</a></li>'
      +'      <li><a href="#">PhD</a></li>'
      +'      <li><a href="#">Drittmittelprojekte</a></li>'
      +'    </ul>'
      +'  </div>'
      +'  <div class="large-12 column">'
      +'  </div>'
      +'</div>').appendTo('footer') */
      $('<p>Hello World!</p>').appendTo('footer');

 /*     $('<div class="last_">'
      +'<div class="row">'
      +'  <div style="padding-left:30px;" class="large-4 column">'
      +'    <p>Copyright © 2013 Hochschule Darmstadt</p>'
      +'  </div>'
      +'  <div class="large-4 column">'
      +'    <p style="text-align:center">Ein Projekt der Hochschule Darmstadt: www.h-da.de</p>'
      +'  </div>'
      +'  <div style="padding-left:182px;" class="large-4 column">'
      +'    <p style="text-align:left">Impessum</p>'
      +'  </div>'
      +'</div>'
      +'</div>').insertAfter('footer');*/

});